<!doctype html>
<html lang="nl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="NXT Museum in Amsterdam: digitale kunst, licht en geluid die je volledig onderdompelen.">
    <title>NXT Museum | Digitale kunst in Amsterdam</title>
    <link rel="icon" type="image/png" href="fotos/nxtlogo.png">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;700&family=Space+Grotesk:wght@400;500;600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link rel="stylesheet" href="styles.css">
    <script src="script.js" defer></script>
</head>
<body>
    <header class="site-header"><a class="brand" href="index.php" aria-label="NXT Museum home">NXT<span>.</span></a><button class="menu-toggle" id="js--menu" type="button" aria-expanded="false" aria-controls="js--nav"><span class="menu-label">Menu</span><span class="menu-icon" aria-hidden="true"><i></i><i></i></span></button></header>
    <nav class="main-navigation" id="js--nav" aria-label="Hoofdnavigatie" aria-hidden="true"><div class="nav-glow" aria-hidden="true"></div><div class="nav-inner"><p class="eyebrow">NXT Museum / Amsterdam Noord</p><ul class="navigation-list"><li><a href="#home">Home <span>01</span></a></li><li><a href="https://nxtmuseum.com/nl/tentoonstelling/" target="_blank" rel="noreferrer">Jouw bezoek <span>02</span></a></li><li><a href="#about">Over ons <span>03</span></a></li><li><a href="https://virtual.nxtmuseum.com/heleen-blanken" target="_blank" rel="noreferrer">Virtuele galerij <span>04</span></a></li><li><a href="engels.php">English <span>05</span></a></li></ul><p class="nav-note">Open dagelijks · Asterweg 22 · Amsterdam</p></div></nav>
    <main id="home">
        <section class="hero" aria-labelledby="hero-title"><img class="hero-image" src="fotos/background.webp" alt="Bezoekers in een kleurrijke installatie van NXT Museum"><div class="hero-shade"></div><div class="hero-content reveal"><p class="eyebrow">Mediakunstmuseum / Amsterdam</p><h1 id="hero-title">Kunst die<br><em>beweegt.</em></h1><div class="hero-bottomline"><p>Een museum voor digitale kunst, nieuwe ideeën en zintuiglijke ontdekkingen.</p><a class="circle-link" href="#about" aria-label="Ontdek NXT Museum"><i class="fas fa-arrow-down"></i></a></div></div><div class="hero-index" aria-hidden="true">01 / 04</div></section>
        <section class="intro section-shell reveal" id="about"><div class="section-label"><span>01</span><span>Het museum</span></div><div class="intro-copy"><h2>De toekomst<br>is <em>nu.</em></h2><div><p>NXT Museum is het eerste museum in Nederland dat zich volledig richt op grootschalige, multidisciplinaire mediakunst. Stap binnen in werelden van licht, geluid en technologie.</p><a class="text-link" href="https://nxtmuseum.com/nl/de-kunst-van-morgen-vandaag/" target="_blank" rel="noreferrer">Ontdek ons verhaal <i class="fas fa-arrow-right"></i></a></div></div></section>
        <section class="gallery section-shell" aria-labelledby="gallery-title"><div class="gallery-heading reveal"><div class="section-label"><span>02</span><span>In beeld</span></div><h2>Ruimtes om<br>in te <em>verdwalen.</em></h2></div><div class="gallery-grid"><figure class="gallery-item gallery-item--wide reveal"><img src="fotos/NXT museum.webp" alt="Lichtinstallatie in NXT Museum" loading="lazy"><figcaption>Shifting Proximities <span>01</span></figcaption></figure><figure class="gallery-item gallery-item--tall reveal"><img src="fotos/UFO_NXT_Museum2.webp" alt="Immersieve UFO-installatie" loading="lazy"><figcaption>Beyond the ordinary <span>02</span></figcaption></figure><figure class="gallery-item gallery-item--small reveal"><img src="fotos/foto1.webp" alt="Kleurrijke digitale kunstprojectie" loading="lazy"><figcaption>New perspectives <span>03</span></figcaption></figure><figure class="gallery-item gallery-item--small reveal"><img src="fotos/foto.webp" alt="Bezoekers beleven een lichtwerk" loading="lazy"><figcaption>In the moment <span>04</span></figcaption></figure></div></section>
        <section class="visit-band reveal" aria-labelledby="visit-title"><div class="visit-inner"><div><p class="eyebrow">Plan je bezoek</p><h2 id="visit-title">Klaar voor<br><em>iets nieuws?</em></h2></div><a class="button button--light" href="https://nxtmuseum.com/nl/tentoonstelling/" target="_blank" rel="noreferrer">Koop tickets <i class="fas fa-arrow-right"></i></a></div></section>
    </main>
    <footer class="site-footer"><div class="footer-top"><a class="brand" href="#home">NXT<span>.</span></a><p>Digitale kunst die je niet alleen bekijkt,<br>maar volledig ervaart.</p></div><div class="footer-grid"><div><p class="footer-title">Volg ons</p><div class="socials"><a href="https://www.instagram.com/nxtmuseum/" aria-label="Instagram" target="_blank" rel="noreferrer"><i class="fab fa-instagram"></i></a><a href="https://www.facebook.com/nxtmuseum/?locale=nl_NL" aria-label="Facebook" target="_blank" rel="noreferrer"><i class="fab fa-facebook-f"></i></a><a href="https://twitter.com/nxtmuseum" aria-label="Twitter" target="_blank" rel="noreferrer"><i class="fab fa-twitter"></i></a></div></div><div><p class="footer-title">Bezoek</p><p>Asterweg 22<br>1031 HP Amsterdam</p></div><div><p class="footer-title">Contact</p><p><a href="mailto:info@nxtmuseum.com">info@nxtmuseum.com</a><br>+31 (0)20 808 04 94</p></div></div><div class="footer-bottom"><span>© <?php echo date('Y'); ?> NXT Museum</span><a href="engels.php">English version</a><span>Amsterdam, NL</span></div></footer>
</body>
</html>